<?php
/**
 * @file
 */

/**
 * Implements hook_init()
 *
 * Adds the livereload javascript so we don't need the browser extension.
 */
function drupal_streamline_dev_page_build(&$page) {
  // The guard-livereload gem includes a copy of the livereload.js script at the same
  // port configured in the livereload guard in the Guardfile
  // Other livereload options available: &mindelay=1000&maxdelay=60000
  $guard_livereload_js_uri = 'http://localhost:35777/livereload.js?host=localhost&port=35777&snipver=1';

  // Try to request the guard copy of livereload
  // First we mount the client:
  Guzzle\Http\StaticClient::mount();
  // Then we pass the client our request url
  $guard_livereload_js = Guzzle::get($guard_livereload_js_uri);

  // If there is a copy, guard is running and we should add the livereload.js script
  // if ($guard_livereload_js->code == 200) {
  //   $page['#attached']['js'][$guard_livereload_js_uri] = array('every_page' => TRUE);
  // }
}

/**
 * Implements hook_custom_theme()
 * @todo - Find implementation for Drupal 8 - hook_custom_theme() appears to be deprecated.
 */

// function drupal_streamline_dev_custom_theme() {
//   // Allow the user to request a particular theme via a query parameter.
//   if (isset($_GET['theme'])) {
//     return $_GET['theme'];
//   }
// }

/**
 * Implements hook_css_alter().
 *
 * Force CSS to be added with link tags, rather than @import. Makes livereload work better.
 */
function drupal_streamline_dev_css_alter(&$css) {
  foreach ($css as $key => $value) {
    $css[$key]['preprocess'] = FALSE;
  }
}
